######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 8 20:14:19 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += sql

# Input
HEADERS += connection.h lhmainwindow.h resultview.h searchpanel.h lhsettings.h
SOURCES += lhmainwindow.cpp main.cpp resultview.cpp searchpanel.cpp lhsettings.cpp
